import { betterAuth } from "better-auth";
import { bearer, organization } from "better-auth/plugins";
import { Algorithm, hash as argonHash, verify as argonVerify } from "@node-rs/argon2";
import pg from "pg";
import { config } from "../config.js";
import { BRAND_NAME } from "../brand.js";

/**
 * Better Auth (spec 04 §1/§2).
 *
 * - email+password with **argon2id** hashing (overrides the built-in scrypt).
 * - server-side sessions (opaque token in the `session` table) for instant revocation.
 * - `bearer` plugin so the desktop client can authenticate with an
 *   `Authorization: Bearer <session-token>` header (token stored in the OS keychain),
 *   in addition to cookies.
 * - `organization` plugin = workspaces/teams: owner/admin/member roles + invitations
 *   (48h expiry per spec).
 *
 * Better Auth wraps this raw pg Pool with its Kysely adapter. Column names are
 * camelCase and quoted; migration 001 (generated by @better-auth/cli) matches.
 */

// argon2id (OWASP default). @node-rs/argon2 already defaults to argon2id; we set
// the algorithm explicitly to satisfy the spec's mandate.
const argonOpts = { algorithm: Algorithm.Argon2id } as const;

export const authPool = new pg.Pool({ connectionString: config.databaseUrl });

// Google social sign-in is opt-in: only wired when both creds are present, so a
// self-hosted server without them just omits the provider (the desktop hides
// the button and email+password keeps working).
export const googleEnabled = Boolean(config.googleClientId && config.googleClientSecret);
const socialProviders = googleEnabled
  ? {
      google: {
        clientId: config.googleClientId!,
        clientSecret: config.googleClientSecret!,
      },
    }
  : undefined;

export const auth = betterAuth({
  appName: BRAND_NAME,
  database: authPool,
  secret: config.jwtSecret,
  baseURL: config.betterAuthUrl,
  basePath: "/api/auth",
  // The desktop client is a Tauri webview whose Origin isn't the server's
  // baseURL, so it must be trusted explicitly (spec 04 §7 in-app login).
  // `tauri://localhost` is the packaged-app origin (macOS/Linux);
  // `http://tauri.localhost` is Windows; `http://localhost:1420` is `tauri dev`.
  trustedOrigins: [
    config.betterAuthUrl,
    "tauri://localhost",
    "http://tauri.localhost",
    "http://localhost:1420",
  ],
  emailAndPassword: {
    enabled: true,
    // MVP: no email round-trip required to sign in (email verification deferred).
    requireEmailVerification: false,
    password: {
      hash: (password: string) => argonHash(password, argonOpts),
      verify: ({ hash, password }: { hash: string; password: string }) =>
        argonVerify(hash, password),
    },
  },
  ...(socialProviders ? { socialProviders } : {}),
  account: {
    // Identity is the email: signing in with Google links to an existing
    // email+password account with the same address (and vice-versa) instead of
    // forking a second account. Google is trusted because it returns a verified
    // email, so the auto-link is safe.
    accountLinking: {
      enabled: true,
      trustedProviders: ["google"],
    },
    // Desktop OAuth runs the Google consent in the system browser while the app
    // (a Tauri webview) initiated /sign-in/social from a *different* cookie jar,
    // so the signed `state` cookie set at sign-in is absent at the callback.
    // State + PKCE still live server-side in the verification table (default
    // storeStateStrategy "database"), single-use and short-lived, so we skip
    // only the redundant cookie check — the same thing Better Auth's own
    // oauth-proxy plugin does for cross-origin flows.
    skipStateCookieCheck: true,
  },
  plugins: [
    bearer(),
    organization({
      creatorRole: "owner",
      invitationExpiresIn: config.invitationExpiresInSeconds, // 48h
    }),
  ],
});

export type Auth = typeof auth;
